---
title: "中文版"
editor: 
  markdown: 
    wrap: 72
---

## 个人简介

刘世航，男，现为广西大学物理科学与工程学院硕士研究生，导师为[李博华](https://orcid.org/0000-0002-3600-0358)。将于2026年9月加入北师大[夏俊卿](https://inspirehep.net/authors/1026564)宇宙学课题组读博。2022年毕业于云南大学物理与天文学院天文菁英班，获理学学士学位。研究兴趣包含21cm宇宙学、第一代天体、暗物质、宇宙大尺度结构的形成与演化；同时也很关注21cm前景处理和机器学习在宇宙学中的应用等细分方向。
这是我的个人主页，你可以在这里找到我的笔记、文章和代码，我现在只是硕士在读，所以内容会比较基础和稚嫩，欢迎指导批评！我希望我的学术生涯能和这个网站一同持续下去！

- 邮箱：sehighs@163.com
- Github: <https://github.com/sehighs>
- ORCID: <https://orcid.org/0009-0000-6270-0617>
- 个人主页：<https://sehighs.github.io>

## 教育背景

- 2023-今 广西大学 物理科学与工程学院 物理学 高能天体物理 研究生
- 2018-2022 云南大学 物理与天文学院 本科生（理学学士）

## 研究兴趣

- 宇宙学 (21cm宇宙学、大尺度结构形成与演化、暗物质、第一代天体)
- 数据处理 (21cm前景扣除、机器学习)
- 统计方法 （相关函数，小波变换）

## 技能
- Python, C
- 21cmFAST, 21cmSense
  
## 论文
- 李博华, **刘世航**, 赵梦麟等， 
  基于鸿蒙21 cm全天平均频谱研究暗物质物理本质及早期宇宙黑洞形成  
  (鸿蒙计划中文版科学白皮书的一部分)
  [中国科学: 物理学 力学 天文学](https://www.sciengine.com/SSPMA/doi/10.1360/SSPMA-2026-0032)，SSPMA预发表
- Hayato Shimabukuro, **Shihang Liu**, Bohua Li.
  Probing Fuzzy Dark Matter in the 21 cm Signal via Wavelet Scattering Transform.
  [arXiv](https://arxiv.org/abs/2512.00402)
- **Shihang Liu** et al. Constraining fuzzy dark matter with the 21-cm power spectrum from Cosmic Dawn and Reionization. [PRD](https://journals.aps.org/prd/abstract/10.1103/zh2b-hhrs), 2025. [arXiv](https://arxiv.org/abs/2508.10176)
- Xinzhong Er, Jiangchuan Yu, Adam Rogers, **Shihang Liu**, Shude Mao. Bias in apparent dispersion measure due to demagnification of plasma lensing on background radio sources. [**MNRAS**](https://academic.oup.com/mnras/article-abstract/510/1/197/6449010?redirectedFrom=fulltext), 2022. 

